### ISSUE TITLE
RPI Cloud Init from /boot 

### ISSUE THREAD

**Issue by jcustenborder** [vmware/photon#1213]
Hey All, 

I'm in a spot where I'm building out several Raspberry PI 4s  and would love it if I could use cloud-init. I've got something working with NoCloud where I have a default configuration of NoCloud that points to /boot. This allows me to configure each RPI instance on boot by maintaining `/boot/meta-data` and `/boot/user-data`. Is there any appetite to add this to the RPI image? I'm happy to contribute back. 

J

**Comment by sshedi** [comment]
@jcustenborder - we already support this from Photon.

We have VMwareGuestInfo & OVF datasource available in Photon.
Explore a bit on https://github.com/vmware/cloud-init-vmware-guestinfo and give an update here.

What you are using is the seed directory concept in cloud-init, you can use the same in OVF data source as well.
OVF usage example: https://github.com/canonical/cloud-init/blob/main/doc/sources/ovf/example/ovf-env.xml

**Comment by jcustenborder** [comment]
@sshedi Sorry about the delay. I was specifically meaning for the Raspberry Pi Image. I've used what you've linked when using a virtual machine on VMWare. It works great. I specifically have the need to configure several Raspberry PI 4s running photon.

**Comment by sshedi** [comment]
Hi, can you please explain what you are doing currently? And what you are expecting from cloud-init?

Can you try making using OVF data source and in ovf-env.xml set seedfrom to /boot?

**Comment by jcustenborder** [comment]
My goal are to do the following steps and have a configured raspberry pi on first boot. 

1. Mac - Image photon to sd card with something like balena etcher
2. Mac - Write /boot/user-data and /boot/meta-data to /boot volume on newly imaged sd card. 
3. PI - Put sd card in pi
4. Pi - boots and runs cloud config. full cloud config has executed.

The above workflow would allow me to image several sd cards, configure them via nocloud, all without booting them. This would also allow me to configure the PIs headless.

Now I'm doing this. Imagine you're doing 30 of these. 

1. Mac - Image photon to sd card with something like balena etcher
2. Bench Pi - put sd card in pi
3. Bench PI - plugin monitor and keyboard
4. Bench PI - login with default password
5. Bench PI - enable ssh as root
6. Bench PI - Restart ssh
7. Mac - Run ansible script to install and configure cloud-init
8. Bench Pi - Shutdown
9. Actual PI - install sd card
10. Actual PI - power on 
    
Right now I have an ansible script that does a lot of this. The out of the box image for the raspberry pi does have cloud init installed. This installs cloud init and configures it to look at `/boot/` with nocloud.  

I'm happy to share the full repo if that helps. It would be amazing if we could have cloud init already installed and configured to look at the boot volume.

```
- hosts: all
  vars:
    cloud_init_meta_data:
      instance-id: "iid-nocloud-{{ new_hostname }}"
      hostname: "{{ new_hostname }}.{{ new_domain }}"
    cloud_init_user_data:
      hostname: "{{ new_hostname }}"
      fqdn: "{{ new_hostname }}.{{ new_domain }}"
      manage_etc_hosts: true
      users:
        - name: root
          lock_passwd: True
        - name: admin
          groups:
            - wheel
          sudo:
            - 'ALL=(ALL) NOPASSWD:ALL'
          ssh_authorized_keys:
            - 'ssh-rsa aSDSasdaSDAsa1'
      power_state:
        delay: "+5"
        mode: reboot
        message: Applying cloud-init configuration
        timeout: 30
        condition: True
  tasks:
  - tdnf:
      name:
        - cloud-init
        - sudo
      state: latest
  - copy:
      dest: /boot/user-data
      content: "#cloud-config\n{{ cloud_init_user_data | to_nice_yaml }}"
  - copy:
      dest: /boot/meta-data
      content: "{{ cloud_init_meta_data | to_nice_yaml }}"
  - copy:
      dest: /etc/dracut.conf.d/broadcom.conf
      content: 'add_drivers+="bcm_phy_lib broadcom"'
  - copy:
      dest: /etc/cloud/cloud.cfg
      src: cloud.cfg.yml
```

Cloud config
```
# The top level settings are used as module
# and system configuration.

# A set of users which may be applied and/or used by various modules
# when a 'default' entry is found it will reference the 'default_user'
# from the distro configuration specified below
users:
   - name: root
     lock_passwd: false

# VMware OVF guest customization.
disable_vmware_customization: true

# If set to true, cloud-init will create fallback netcfg
# In Photon, we have default network settings already, hence if network
# settings are not explicitly given in metadata, don't use fallback netcfg.
use_fallback_netcfg: false

# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the default $user
disable_root: true

# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: false

# OVF has been removed in default list because recent feature addition
# introduces a 15 sec delay during boot
datasource_list: ['NoCloud']
# Example datasource config
# datasource:
#    Ec2:
#      metadata_urls: [ 'blah.com' ]
#      timeout: 5 # (defaults to 50 seconds)
#      max_wait: 10 # (defaults to 120 seconds)

# Set allow_raw_data to true if you want OVF to support raw data feature
# this will wait 15 sec for cust.cfg
datasource:
  NoCloud:
    seedfrom: file:///boot/


# The modules that run in the 'init' stage
cloud_init_modules:
 - migrator
 - seed_random
 - bootcmd
 - write-files
 - growpart
 - resizefs
 - disk_setup
 - mounts
 - set_hostname
 - update_hostname
 - update_etc_hosts
 - rsyslog
 - users-groups
 - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
 - set-passwords
 - yum-add-repo
 - ntp
 - timezone
 - disable-ec2-metadata
 - runcmd

unverified_modules:
 - yum-add-repo
 - ntp

# The modules that run in the 'final' stage
cloud_final_modules:
 - package-update-upgrade-install
 - puppet
 - chef
 - mcollective
 - salt-minion
 - reset_rmc
 - refresh_rmc_and_interface
 - rightscale_userdata
 - scripts-vendor
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - ssh-authkey-fingerprints
 - keys-to-console
 - phone-home
 - final-message
 - power-state-change

# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
   # This will affect which distro class gets used
   distro: photon
   default_user:
     name: photon
     lock_passwd: True
     gecos: PhotonOS
     groups:
       - wheel
     sudo:
       - "ALL=(ALL) NOPASSWD:ALL"
     shell: /bin/bash
   # Other config here will be given to the distro class and/or path classes
   paths:
      cloud_dir: /var/lib/cloud/
      templates_dir: /etc/cloud/templates/

   ssh_svcname: sshd

#manage_etc_hosts: true
```
