### ISSUE TITLE
Can't install zabbit-agent

### ISSUE THREAD

**Issue by dronmaxman** [vmware/photon#1401]
### Describe the bug

root@photon-machine [ ~ ]# tdnf install zabbix-agent
1. package zabbix-agent-5.2.7-1.el8.x86_64 requires libcrypto.so.1.1()(64bit), but none of the providers can be installed
Found 1 problem(s) while resolving
Error(1301) : Solv general runtime error

### Reproduction steps

1. Add rpm -Uvh  https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/zabbix-release-5.2-1.el8.noarch.rpm
2. tdnf clean all
3. tdnf install zabbix-agent
...

### Expected behavior

Installed and working application.

### Additional context

root@photon-machine [ ~ ]# cat /etc/*release*
DISTRIB_ID="VMware Photon OS"
DISTRIB_RELEASE="4.0"
DISTRIB_CODENAME=Photon
DISTRIB_DESCRIPTION="VMware Photon OS 4.0"
NAME="VMware Photon OS"
VERSION="4.0"
ID=photon
VERSION_ID=4.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
VMware Photon OS 4.0
PHOTON_BUILD_NUMBER=2f5aad892

**Comment by tapakund** [comment]
removing bug label as this error is expected. Photon OS 4.0 comes with default openssl 3.x and https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/zabbix-release-5.2-1.el8.noarch.rpm is expecting openssl 1.1.x on the machine, mostly because this has been built with openssl 1.1.x. 
For time being, you can you use the documentation here https://www.zabbix.com/documentation/6.2/en/manual/installation/install to build and install zabbix on a Photon 4.0 machine.

**Comment by dronmaxman** [comment]
`Photon OS 4.0 comes with default openssl 3.x and`
Are you talking about rc1, rc2 or GA? According to this link it is written that openssl 1.1.1 is used.
https://github.com/vmware/photon/wiki/What-is-New-in-Photon-OS-4.0

**Comment by tapakund** [comment]
Sorry, i meant 4.0 rev2, pls refer: https://vmware.github.io/photon/docs/whats-new-photon-os-4-rev2-/
Actually we GA'ed with openssl 1.1.1, and later updated to openssl 3.0. Currently Photon OS 4.0 have openssl 3.0.7 : https://github.com/vmware/photon/blob/4.0/SPECS/openssl/openssl.spec

**Comment by dronmaxman** [comment]
Thanks for the hint)

**Comment by ngl95lam** [comment]
Hi, I am using vm photon4 and also got this error.
For now, I still can not find anyway to install zabbix-agent because of libcrypto.so.1.1()(64bit) problem.
How did you install zabbix-agent or did you pass this problem?

Plz help, thank you!

**Comment by dronmaxman** [comment]
Using zabbix in docker

```yml
version: '3.5'

services:
 zabbix-agent:
  user: root
  container_name: zabbix-agent2
  image: zabbix/zabbix-agent2:alpine-6.4-latest
  ports:
   - "10050:10050"
  group_add:
    - "999"
  volumes:
   - /etc/localtime:/etc/localtime:ro
#   - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
#   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
#   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
#   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   -  /var/run/docker.sock:/var/run/docker.sock:ro
  environment:
    - ZBX_HOSTNAME=vs-kv-web-oo01
    - ZBX_SERVER_HOST=91.231.206.21
#    - ZBX_SERVER_HOST=zabbix-px01.deps.ua
#    - ZBX_ACTIVESERVERS=91.231.206.46,91.231.206.21
#    - ZBX_DEBUGLEVEL=4
#    - ZBX_ACTIVE_ALLOW=true
  deploy:
   resources:
    limits:
      cpus: '0.2'
      memory: 128M
    reservations:
      cpus: '0.1'
      memory: 64M
   mode: global
#  env_file:
#   - ./env_vars/.env_agent
  network_mode: "host"
  privileged: true
  pid: "host"
  stop_grace_period: 5s
```
