### ISSUE TITLE
Adding trusted root certificates to the server

### ISSUE THREAD

**Issue by Vanarga** [vmware/photon#592]
How do you add additional trusted root certificates to Photon?

**Comment by ppadmavilasom** [comment]
add them to /etc/ssl/certs and run c_rehash (brought in by pkg openssl-c_rehash)

doc on c_rehash - https://www.openssl.org/docs/man1.0.2/apps/c_rehash.html

**Comment by everett-toews** [comment]
@ppadmavilasom I'm on these version of photon and openssl

```bash
# cat /etc/os-release
NAME="VMware Photon"
VERSION="1.0"
ID=photon
VERSION_ID=1.0
PRETTY_NAME="VMware Photon/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"

# openssl version
OpenSSL 1.0.2h-fips  3 May 2016

# c_rehash
bash: c_rehash: command not found
```

but the `c_rehash` command isn't there. What am I missing?

**Comment by ppadmavilasom** [comment]
root [ / ]# tdnf provides */c_rehash
openssl-c_rehash-1.0.2l-2.ph2.x86_64 : openssl perl scripts
Repo	 : photon

**Comment by odg0318** [comment]
@ppadmavilasom 
root [ / ]# tdnf provides */c_rehash
curl#60: Peer certificate cannot be authenticated with given CA certificates
Error: Failed to synchronize cache for repo 'VMware Photon Linux 1.0(x86_64)Updates' from 'https://dl.bintray.com/vmware/photon_updates_1.0_x86_64'
Disabling Repo: 'VMware Photon Linux 1.0(x86_64)Updates'
curl#60: Peer certificate cannot be authenticated with given CA certificates
Error: Failed to synchronize cache for repo 'VMware Photon Extras 1.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_extras'
Disabling Repo: 'VMware Photon Extras 1.0(x86_64)'
curl#60: Peer certificate cannot be authenticated with given CA certificates
Error: Failed to synchronize cache for repo 'VMware Lightwave 1.0(x86_64)' from 'https://dl.bintray.com/vmware/lightwave'
Disabling Repo: 'VMware Lightwave 1.0(x86_64)'
curl#60: Peer certificate cannot be authenticated with given CA certificates
Error: Failed to synchronize cache for repo 'VMware Photon Linux 1.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_1.0_x86_64'
Disabling Repo: 'VMware Photon Linux 1.0(x86_64)'
Error(1661) : No data available

How can I fix it?

**Comment by ppadmavilasom** [comment]
1.0 installs come with ca-certificates which provide certificate bundle necessary for this validation.
please check rpm -q ca-certificates to see if its installed. 
could you please check your machine date to see if its current.
Other option is to browse this url: https://vmware.bintray.com/photon_release_1.0_x86_64/x86_64/
and download using curl -k and install using rpm -i

**Comment by odg0318** [comment]
@ppadmavilasom How can I get photon version in installed os?
I installed docker images from the following url; https://github.com/vmware/harbor/releases
And clair image you can see below is downloaded from the url. 

```
$ docker exec -it clair rpm -q ca-certificates
ca-certificates-20160109-5.ph1.x86_64
$ docker exec -it clair date -u
Tue Nov  7 01:13:24 UTC 2017
$ date -u
Tue Nov  7 01:13:30 UTC 2017
```

**Comment by odg0318** [comment]
I tested my issue on two different environments; mac, ubuntu.
On Ubuntu, it works fine but on Mac not.
Is there something difference depending on the kind of os?

**Comment by odg0318** [comment]
And I found photon OS version.
```
# cat /etc/photon-release
VMware Photon Linux 1.0
PHOTON_BUILD_NUMBER=62c543d
```

**Comment by odg0318** [comment]
In my case, certificate error occur from my company's firewall.
Anyway, how can I add additional root CA to photon OS?
I have a trouble to access repository via `tdnf`.

**Comment by odg0318** [comment]
@ppadmavilasom Can you help me to add my root CA without internet?
As I said as above, I found `c_hash.sh` utility in `/etc/ssl/certs/misc` which calculate hash value.

But when I checked whether root ca is installed well or not, it doesn't work well. Curl still shows error during connecting to TLS url.

**Comment by ppadmavilasom** [comment]
workaround is to download the rpms from https://vmware.bintray.com/photon_release_1.0_x86_64/x86_64/openssl-c_rehash-1.0.2h-2.ph1.x86_64.rpm and install via rpm -i

if additional packages are required, use the same link without the file name and find others.

**Comment by odg0318** [comment]
@ppadmavilasom 
At first, I am really appreciate of your concern.
I tried to download and install `openssl-c_rehash` and met an obstacle.
```
root [ / ]# rpm -i openssl-c_rehash-1.0.2h-2.ph1.x86_64.rpm
error: Failed dependencies:
        perl-DBIx-Simple is needed by openssl-c_rehash-1.0.2h-2.ph1.x86_64
```
And then I checked whether `perl-DBIx-Simple` is in the package list but doesn't exist.

**Comment by odg0318** [comment]
I found workaround when certification error occurred.

The first solution is to modify repo url from https to http in `/etc/yum.repos.d/*.repo`, which skip to use tls url.

The second one is to manually download and install `openssl-c_rehash`.
Its dependancies are described in the following list.
```
gdbm                                                                                  x86_64                          1.11-2.ph1                                                         463.17 k
perl                                                                                  x86_64                          5.22.1-5.ph1                                                        48.22 M
perl-Object-Accessor                                                                  noarch                          0.48-2.ph1                                                          31.48 k
perl-DBI                                                                              x86_64                          1.634-2.ph1                                                          1.78 M
perl-DBD-SQLite                                                                       x86_64                          1.50-2.ph1                                                           7.88 M
perl-DBIx-Simple                                                                      noarch                          1.35-2.ph1                                                          60.20 k
openssl-c_rehash                                                                      x86_64                          1.0.2l-1.ph1                                                         4.92 k
```

The third one is to manually calculate using `/etc/ssl/misc/c_hash` and make symbolic link in `/etc/ssl/certs`.

Thanks a lot again.

**Comment by ppadmavilasom** [comment]
@odg0318 much better solution. the way i suggested, you had to download rpms one by one and fulfill dependencies. i have to remember the http url is available as well. good find!

**Comment by ununseptium** [comment]
This issue actually not solves the initial issue rn. I personally tried running `c_rehash` on the certs i added and it just creates symlinks and not adds those certs to the cert bundle in `/etc/pki/tls/certs/ca-bundle.crt` which need to happen right?

I looked at the spec for photon's ca-cert handling and there're a few scripts etc. in `/usr/bin/` but this all seems like it's not supposed to be made like that.

Isn't there're a tool that does that or am i missing something crucial?

**Comment by woertz** [comment]
`/usr/bin/rehash_ca_certificates.sh` worked for me. `/etc/pki/tls/certs/ca-bundle.crt` is now up-to-date.

**Comment by MasashiTeruya** [comment]
1. Put root certificate as pem file under /etc/ssl/certs/
1. Install and Execute rehash script to update /etc/pki/tls/certs/ca-bundle.crt
```
# tdnf install -y openssl-c_rehash
# rehash_ca_certificates.sh
```

**Comment by LaXiS96** [comment]
For anyone stumbling on this issue who cannot install `openssl-c_rehash` because of, for example, an enterprise HTTPS firewall requiring a self-signed intermediate certificate, here is a variation on the previous solution.
[`rehash_ca_certificates.sh`](https://github.com/vmware/photon/blob/822d46139f094a52dc557679c50c2009fdc7c3a0/SPECS/openssl/rehash_ca_certificates.sh) is a simple script that calls `openssl rehash` and then concatenates PEM files from `/etc/ssl/certs` into `/etc/pki/tls/certs/ca-bundle.crt`.

Therefore without installing any additional package (as of 4.0 Rev2), all you need to do is:
```sh
cp mycertificate.pem /etc/ssl/certs/
openssl rehash /etc/ssl/certs
cat /etc/ssl/certs/*.pem >/etc/pki/tls/certs/ca-bundle.crt
```

**Comment by instanceofmel** [comment]
For anyone who wants to install a self-signed cert to containerd in order to pull images from a private registry on a Tanzu Kubernetes node: this DaemonSet has worked for me. I've used the answer for Ubuntu based nodes from https://stackoverflow.com/a/62981618/18889642 and added the solutions for Photon suggested here.

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-ca
  namespace: kube-system
  labels:
    k8s-app: registry-ca
spec:
  selector:
    matchLabels:
      name: registry-ca
  template:
    metadata:
      labels:
        name: registry-ca
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: registry-ca
          image: busybox
          securityContext:
            privileged: true
          command: ["sh"]
          args:
            - -c
            - |
              cp /home/core/registry-ca /etc/ssl/certs/registry-ca.pem
              nsenter --mount=/proc/1/ns/mnt -- sh -c "tdnf -y install openssl-c_rehash && c_rehash /etc/ssl/certs && cat /etc/ssl/certs/*.pem >/etc/pki/tls/certs/ca-bundle.crt && systemctl restart containerd"
          volumeMounts:
            - name: etc-ssl-certs
              mountPath: /etc/ssl/certs
            - name: ca-cert
              mountPath: /home/core
      terminationGracePeriodSeconds: 30
      volumes:
        - name: etc-ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: ca-cert
          secret:
            secretName: registry-ca
      containers:
        - name: wait
          image: k8s.gcr.io/pause:3.1
```
