### ISSUE TITLE
photon2.0 is missing rpm/yum bindings

### ISSUE THREAD

**Issue by mzeier** [vmware/photon#879]
Using the Ansible `package` module tosses the following errors:

```
failed: [packer] (item=jq) => {"changed": false, "item": "jq", "msg": "The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}
```

Packer adds the following:
```
        "/usr/bin/tdnf makecache",
        "/usr/bin/tdnf install -y python2",
        "/usr/bin/tdnf install -y python-rpm rpm python3-yum"
```

The Ansible task I'm trying to run is:
```
    - name: Install common utilities
      packages: name="{{ item }}" state=latest update_cache=yes
      loop:
        - jq
        - iotop
        - iftop
      ignore_errors: true
```

Which package or packages am I missing?
